Repository XAP-Software/blog.xap.group, pull requests merged in 2022-05, with the labels that each got.

#7 Create django-admin-sortable2 article
  _posts/2022-04-28-django_admin_sortable2.md
Labels: on review

#12 Created pop-up with params in Next.js
  _posts/2022-05-06-nextjs_popup_with_params.md
Labels: on review

#17 New article has been written
  _posts/2022-05-13-how_to_open_a_restaurant.md
Labels: on review

#13 Created a new article Setting-up-replication
  _posts/2022-05-06-Setting-up-replication.md
  article_images/data_provisioning_agent1.png
  article_images/data_provisioning_agent2.png
  article_images/data_provisioning_agent3.png
  article_images/data_provisioning_agent4.png
  article_images/data_provisioning_agent5.png
  article_images/data_provisioning_agent6.png
  article_images/data_provisioning_agent7.png
  article_images/database_preconfiguration1.png
  article_images/database_preconfiguration2.png
  article_images/database_preconfiguration3.png
  article_images/remote_source1.png
  article_images/remote_source2.png
Labels: on review

#16 Create django apache deploy article
  _posts/2022-05-12-django_apache_deploy.md
Labels: on review

#15 How to create switch statement inside rendering method in Next.js?
  _posts/2022-05-11-switch_statement_next_js.md
Labels: on review

#21 Article updated
  _posts/2022-05-07-Axios-interceptors.md
Labels: on review

#19 How to send emails using Django and Postfix?
  _posts/2022-05-21-django_postfix_email_sending.md
Labels: Checked up

#20 Create next-sitemap post
  _posts/2022-05-24-nextjs_sitemap_robots_txt.md
Labels: on review, Checked up

#22 How to create font-family with custom font?
  _posts/2022-05-25-font_family_creating.md
Labels: Checked up
